ttt
dimaglud/vysota_charity pull request #4
Opened 2023-11-22 16:20 UTC by bOOsh789

2023-11-23 11:21 UTC, bOOsh789 commented
Димон, где комментарии? Не видать..

2023-11-23 20:23 UTC, dimaglud requested changes

2023-11-24 14:15 UTC, bOOsh789 commented on frontend/helpto.html
> +<!-- This setup is not suitable for production. -->
убрать весь код после <body> ?

2023-11-24 14:19 UTC, bOOsh789 commented on frontend/assets/site.css
> +  color: #00817E;
Ок. Написал
.menu-item a {
  color: #00817E;
  text-decoration: none;
}

2023-11-24 14:24 UTC, bOOsh789 commented on frontend/assets/site.css
> +.article-item-h2 {
Ты про footer и header? Понял.

2023-11-27 20:25 UTC, merged